# Generated by Django 5.2 on 2025-04-11 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='courses')),
                ('name', models.CharField(max_length=255)),
                ('monthly_fee', models.DecimalField(blank=True, decimal_places=2, help_text='Tarifa mensual del curso.', max_digits=10, null=True)),
                ('total_payments', models.PositiveIntegerField(blank=True, help_text='Número total de pagos mensuales.', null=True)),
                ('enrollment_fee', models.DecimalField(blank=True, decimal_places=2, help_text='Tarifa única de inscripción.', max_digits=10, null=True)),
                ('is_visible', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
